pull_requests:
  do_not_increment_build_number: true
version: '{build}'
branches:
  only:
  - master
shallow_clone: true
image: 
  - Visual Studio 2017
  - Ubuntu
build_script:
  - mkdir build
  - cd build
  - cmake ../byond-extools
  - cmd: cmake --build . --config RelWithDebInfo
  - sh: sudo apt-get install -y gcc-multilib g++-multilib
  - sh: make

for:
- matrix:
    only:
      - image: Visual Studio 2017
  artifacts:
    - path: build/RelWithDebInfo/byond-extools.dll
    - path: build/RelWithDebInfo/byond-extools.pdb

- matrix:
    only:
      - image: Ubuntu
  artifacts:
    - path: build/libbyond-extools.so
