#pragma once
#include "instruction.h"

ADD_INSTR(END)
ADD_INSTR_ARG(JMP, 1)
ADD_INSTR_ARG(JZ, 1)
ADD_INSTR(RET)
ADD_INSTR_CUSTOM(CALL)
ADD_INSTR_CUSTOM(CALLNR)
ADD_INSTR_ARG(CALLPATH, 1)
ADD_INSTR(CALLPARENT)
ADD_INSTR_CUSTOM(CALLGLOB)
ADD_INSTR_ARG(CALLNAME, 1)
ADD_INSTR_ARG(JMP2, 1)
ADD_INSTR_ARG(JNZ, 1)
ADD_INSTR_ARG(CALL_LIB, 1)
