#pragma once

#include "instruction.h"
#include "disassembler.h"


ADD_INSTR_ARG(NEW, 1)
ADD_INSTR_ARG(FORMAT, 2)
ADD_INSTR(OUTPUT)
ADD_INSTR(TEST)
ADD_INSTR_ARG(NEWLIST, 1)
ADD_INSTR_VAR(GETVAR)
ADD_INSTR_VAR(SETVAR)
ADD_INSTR_ARG(PUSHI, 1)
ADD_INSTR(POP)
ADD_INSTR_ARG(ITERLOAD, 2)
ADD_INSTR(ITERNEXT)
ADD_INSTR(ITERATOR_PUSH)
ADD_INSTR(ITERATOR_POP)
ADD_INSTR_CUSTOM(PUSHVAL)
ADD_INSTR(LISTGET)
ADD_INSTR(LISTSET)
ADD_INSTR_ARG(POPN, 1)
ADD_INSTR(CHECKNUM)
ADD_INSTR_ARG(FOR_RANGE, 3)
ADD_INSTR(GETFLAG)
ADD_INSTR_CUSTOM(ISINLIST)
ADD_INSTR(ICON_STATES_MODE)
ADD_INSTR(LPUSH_CACHE)
ADD_INSTR(SET_CACHE)