#pragma once
#include "instruction.h"


ADD_INSTR_CUSTOM(OUTPUT_FORMAT)
ADD_INSTR(FINDTEXT)
ADD_INSTR(REPLACETEXT)
ADD_INSTR(REPLACETEXTEX)
ADD_INSTR(JSON_ENCODE)
ADD_INSTR(JSON_DECODE)
ADD_INSTR_ARG(REGEX_NEW, 1)
ADD_INSTR(COPYTEXT)
ADD_INSTR(SPLITTEXT)
