name: Make and publish linux .so

on:
  push:
    branches: '*'
    tags: v*
  pull_request:
    branches: '*'

defaults:
  run:
    working-directory: byond-extools


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: make build directory
      run: |
        mkdir build

    - name: run cmake
      run: |
        cd build
        cmake ..

    - name: run make
      run: |
        cd build
        make

    - uses: actions/upload-artifact@v2
      with:
        name: libbyond-extools.so
        path: byond-extools/build/libbyond-extools.so
